[package]
name = "gql2sql-worker"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
cfg-if = "0.1.2"
worker = "0.0.11"
serde_json = "1.0.91"
serde = { version = "1.0.152", features = ["derive"] }
graphql-parser = "0.4.0"
gql2sql = { path = "../gql2sql" }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.1", optional = true }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "z"
