[workspace]

members = [
    "app-backend",
    "gql2sql",
    "gql2sql_wasm",
    "gql2sql_server",
    "gql2sql_node",
    "gql2sql_lambda",
    "gql2sql_worker",
    "gql2sql_deno",
    "cache_tags",
]
