[package]
name = "gql2sql"
version = "0.2.2"
edition = "2021"
description = "GraphQL to SQL transpiler"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/brevitybuilder/gql2sql"
repository = "https://github.com/brevitybuilder/gql2sql"
readme = "../README.md"

[dependencies]
anyhow = "1.0"
graphql-parser = "0.4"
sqlparser = "0.32"

[dev-dependencies]
criterion = "0.4"
pretty_assertions = "1.3"

[[bench]]
name = "transform"
harness = false
