[package]
name = "gql2sql"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
graphql-parser = "0.4.0"
sqlparser = "0.28.0"

[dev-dependencies]
criterion = "0.4.0"
pretty_assertions = "1.3.0"

[[bench]]
name = "transform"
harness = false
