[package]
name = "gql2sql"
version = "2.0.2"
edition = "2021"
description = "GraphQL to SQL transpiler"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/brevitybuilder/gql2sql"
repository = "https://github.com/brevitybuilder/gql2sql"
readme = "../README.md"

[dependencies]
anyhow = "1.0"
graphql-parser = "0.4"
async-graphql-parser = "5.0.8"
async-graphql-value = "5.0.8"
serde_json = "1.0.96"
sqlparser = "0.33"
indexmap = "1.9.3"
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.4"
insta = { version = "1.29.0", features = ["yaml"] }
pretty_assertions = "1.3"

[[bench]]
name = "transform"
harness = false

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
