[package]
name = "gql2sql"
version = "3.0.17"
edition = "2021"
description = "GraphQL to SQL transpiler"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/brevitybuilder/gql2sql"
repository = "https://github.com/brevitybuilder/gql2sql"
readme = "../README.md"

[dependencies]
anyhow = "1.0"
graphql-parser = "0.4"
async-graphql-parser = "6.0.4"
async-graphql-value = "6.0.4"
simd-json = "=0.10.5"
sqlparser = "0.37"
indexmap = "2.0.0"
lazy_static = "1.4.0"
regex = "1.9.4"

[dev-dependencies]
criterion = "0.5"
insta = { version = "1.31.0", features = ["yaml"] }
pretty_assertions = "1.4"

[[bench]]
name = "transform"
harness = false

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[build]
rustflags = ["-C", "target-cpu=native"]
rustdocflags = ["-C", "target-cpu=native"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]

[target.wasm32-wasi]
rustflags = ["-C", "target-feature=+simd128"]
