[package]
name = "gql2sql"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
graphql-parser = "0.4"
sqlparser = "0.30"

[dev-dependencies]
criterion = "0.4"
pretty_assertions = "1.3"

[[bench]]
name = "transform"
harness = false
