[build]
rustflags = ["-C", "target-cpu=native"]
rustdocflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-musl]
rustflags = [ "-C", "target-feature=-crt-static,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]
rustdocflags = ["-C", "target-feature=+simd128"]

[target.wasm32-wasi]
rustflags = ["-C", "target-feature=+simd128"]
rustdocflags = ["-C", "target-feature=+simd128"]
