app = "brevity-app-backend"

kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  strategy = "bluegreen"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  enable_consul = true

[[services]]
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 250
    soft_limit = 200
    type = "requests"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "600s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"
    timeout = 5000
    tls_skip_verify = false
    [services.http_checks.headers]
