[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "gql2sql_node"
version = "0.1.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
napi = "2"
napi-derive = "2"
gql2sql = { path = "../gql2sql" }
async-graphql-parser = "5.0.7"
cached = "0.42.0"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
