[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "gql2sql_node"
version = "2.0.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
napi = { version = "2", features = ["serde-json", "error_anyhow", "anyhow"] }
napi-derive = "2"
gql2sql = { path = "../gql2sql" }
async-graphql-parser = "5.0.10"
anyhow = "1.0.72"
simd-json = "0.10.3"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
