[package]
authors = ["Nick Randall <nick@brevity.io>"]
edition = "2021"
name = "gql2sql_node"
version = "2.0.18"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
napi = { version = "2", features = ["serde-json", "error_anyhow", "anyhow"] }
napi-derive = "2"
gql2sql = { path = "../gql2sql" }
async-graphql-parser = "6.0.6"
anyhow = "1.0.75"
simd-json = "=0.10.5"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
