/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface GqlResult {
  sql: string
  params?: Array<any>
}
export function gql2Sql(query: string, vars?: any | undefined | null): GqlResult | null
