name: WASM
'on':
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - .github/workflows/CI.yml
      - gql2sql/**
      - gql2sql-wasm/**
      - Cargo.lock
  pull_request: null
defaults:
  run:
    working-directory: gql2sql-wasm
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Test
        run: RUSTFLAGS='-C target-feature=+simd128' wasm-pack test --chrome  --headless

      - name: Build
        run: RUSTFLAGS='-C target-feature=+simd128' wasm-pack build --release --target web --scope brevity-builder

      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          cd pkg
          npm publish --access public

