name: WASM
'on':
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - .github/workflows/CI.yml
      - gql2sql/**
      - gql2sql-wasm/**
      - Cargo.lock
  pull_request: null
defaults:
  run:
    working-directory: gql2sql-wasm
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Test
        run: RUSTFLAGS='-C target-feature=+simd128' wasm-pack test --chrome --headless

      - name: Build
        run: RUSTFLAGS='-C target-feature=+simd128' wasm-pack build --release --target web --scope brevity-builder

      - name: Publish
        if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd pkg
          npm publish --access public

